---

- name: Add hostname in hosts file
  lineinfile: dest=/etc/hostname line="raspberrypi" state=absent

- name: Add hostname in hosts file
  lineinfile: dest=/etc/hostname line="{{hostname}}" state=present

- name: Add hostname in hosts file
  lineinfile: dest=/etc/hosts line="127.0.0.1     {{hostname}}"

- name: Remove raspberrypi from hosts file
  lineinfile: dest=/etc/hosts regexp="\sraspberrypi\s*$" state=absent

