---

- name: set pi user credentials
  user: name=pi state=present password={{password}} shell=/bin/bash

- name: Prevent raspi-config running on first login
  file: path=/etc/profile.d/raspi-config.sh state=absent

