---

- name: Install base packages selection
  apt: pkg={{item}} state=installed
  with_items:
    - pi-bluetooth
    - bluetooth
    - bluez 
    - python-gobject
    - python-pygame
    - python-cwiid
    - python-serial
    - python-daemon
    - python-dev
    - python-alsaaudio
    - wiringpi
    - moc

- name: Use pip to install wiringpi
  shell: pip -q install wiringpi

