---

- name: Ensuring that pi a ssh key
  user: name=pi generate_ssh_key=yes

- name: Ensure sshd listen to port 22
  lineinfile: dest=/etc/ssh/sshd_config regexp="^Port" line="Port 22" state=present
  notify: Restart sshd

